canal:
  server: 192.168.56.100
  destination: instance
  mode: rabbitMQ
  vhost: canal
  user-name: root
  password: root
  async: false
spring:
  application:
    name: canal-example
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.100:3306/test
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        # Method threw 'org.hibernate.LazyInitializationException' exception. Cannot evaluate
        enable_lazy_load_no_trans: true
