spring:
  application:
    name: canal-example
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.80:3306/test
    username: root
    password: root
  jooq:
    sql-dialect: mysql
  flyway:
    baseline-on-migrate: true
